apiVersion: v1
kind: ConfigMap
metadata:
  name: config-demo
data:
  # Here we define key-value pairs for configuration settings
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys - Here is an example of embedding a properties file content
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true   