services:
   vprodb:
      build:
         context: ./Exercise3/db
      image: sadishdash/vprofiledb
      container_name: vprodb
      ports:
         - "3306:3306"
      volumes:
         - vprodbdata:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=vprodbpass

   vprocache01:
      image: memcached
      container_name: vprocache01
      ports:
         - "11211:11211"    
      
   vpromq01:
      image: rabbitmq
      container_name: vpromq01
      ports:
         - "5672:5672"  
      environment:
         - RABBITMQ_DEFAULT_PASS=guest
         - RABBITMQ_DEFAULT_USER=guest

   vproapp:
      build:
         context: ./Exercise3/app
      image: sadishdash/vprofileapp
      container_name: vproapp
      ports:
         - "8080:8080"
      volumes:
         - vproappdata:/usr/local/tomcat/webapps

   vproweb:
      build:
         context: ./Exercise3/web
      image: sadishdash/vprofileweb
      container_name: vproweb
      ports:
         - "80:80"
   

volumes:
   vprodbdata: {}
   vproappdata: {}
