# Creating a pod with a single container running a Django Todo application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-deployment # Pods created by this Deployment will have names that start with django-todo-deployment. django-todo-deployment-<replicaset-hash>-<pod-suffix>
  namespace: my-django-app
  labels:
    app: django-app

spec: # Deployment specifications
  replicas: 4
  selector:
    matchLabels: 
      app: django-app
  
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-todo-container
        image: sadishdash/django_app_todo:latest
        ports:
        - containerPort: 8001 # Exposing port 8001 on the container
        
# kubectl apply -f deployment.yaml