services:
  node-app:
    image: sadishdash/node_todo:latest
    container_name: todo-app
    ports:
     - "8001:8000"
    deploy:
      replicas: 2

  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test123"
    deploy:
      replicas: 2

# docker stack create -c deployment.yaml <name-of-service>